

DROP TABLE IF EXISTS `COLLEGE`;
DROP TABLE IF EXISTS `USER`;

CREATE TABLE `COLLEGE` (
  `COLLEGE_ID` BIGINT NOT NULL AUTO_INCREMENT,
  `COLLEGE_NAME` VARCHAR(45) NOT NULL,
  `STREET` VARCHAR(45) NOT NULL,
  `STATE` VARCHAR(45) NOT NULL,
  `CITY` VARCHAR(45) NOT NULL,
  `ZIP_CODE` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`COLLEGE_ID`)
  );
  
  
 CREATE TABLE `USER` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `USER_NAME` VARCHAR(45) NOT NULL,
  `PASSWORD` VARCHAR(45) NOT NULL,
  `CREATED_TIME` DATETIME NOT NULL,
  `UPDATED_TIME` DATETIME NULL,
  `USER_TYPE` VARCHAR(45) NOT NULL,
  `STREET` VARCHAR(45) NOT NULL,
  `STATE` VARCHAR(45) NOT NULL,
  `CITY` VARCHAR(45) NOT NULL,
  `ZIP_CODE` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `USER_NAME_UNIQUE` (`USER_NAME` ASC)
  );
     