DROP schema IF EXISTS `jpa_jbd`;

CREATE schema IF NOT EXISTS `jpa_jbd`;
use `jpa_jbd`;

DROP TABLE IF EXISTS `USER`;
  
CREATE TABLE `USER` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `USER_NAME` VARCHAR(45) NOT NULL,
  `PASSWORD` VARCHAR(45) NOT NULL,
  `CREATED_TIME` DATETIME NOT NULL,
  `UPDATED_TIME` DATETIME NULL,
  `USER_TYPE` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `USER_NAME_UNIQUE` (`USER_NAME` ASC)
  );
  
DROP TABLE IF EXISTS `Contacts`;
CREATE TABLE `Contacts` (
  `ID` INT NOT NULL,
  `CONTACT_NO` VARCHAR(45) NOT NULL,
  `CONTACT_TYPE` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`, `CONTACT_NO`, `CONTACT_TYPE`)
);
  
     